# Generated by Django 5.1 on 2024-09-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_hours', models.PositiveIntegerField()),
                ('failure_description', models.TextField()),
                ('spare_parts_used', models.TextField()),
                ('recovery_date', models.DateField()),
                ('downtime', models.DurationField()),
                ('failure_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_nodes', to='machines.modelreference')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='machines.machine')),
                ('recovery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_methods', to='machines.modelreference')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'Service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
