# Generated by Django 5.1 on 2024-09-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('groups', models.CharField(choices=[('client', 'Клиент')], max_length=50, verbose_name='Группы пользователей')),
            ],
            options={
                'verbose_name': 'Справочник пользователей',
                'verbose_name_plural': 'Справочники пользователей',
            },
        ),
        migrations.CreateModel(
            name='ModelDrive_axle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('drive_axle', 'Модель ведущего моста')], max_length=50, verbose_name='Категория модели')),
            ],
            options={
                'verbose_name': 'Справочник модели',
                'verbose_name_plural': 'Справочники моделей',
            },
        ),
        migrations.CreateModel(
            name='ModelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('engine', 'Модель двигателя')], max_length=50, verbose_name='Категория модели')),
            ],
            options={
                'verbose_name': 'Справочник модели',
                'verbose_name_plural': 'Справочники моделей',
            },
        ),
        migrations.CreateModel(
            name='ModelEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('equipment', 'Модель техники')], max_length=50, verbose_name='Категория модели')),
            ],
            options={
                'verbose_name': 'Справочник модели',
                'verbose_name_plural': 'Справочники моделей',
            },
        ),
        migrations.CreateModel(
            name='ModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('engine', 'Модель двигателя'), ('transmission', 'Модель трансмиссии'), ('drive_axle', 'Модель ведущего моста'), ('steering_axle', 'Модель управляемого моста'), ('equipment', 'Модель техники')], max_length=50, verbose_name='Категория модели')),
            ],
            options={
                'verbose_name': 'Справочник модели',
                'verbose_name_plural': 'Справочники моделей',
            },
        ),
        migrations.CreateModel(
            name='ModelSteering_axle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('steering_axle', 'Модель управляемого моста')], max_length=50, verbose_name='Категория модели')),
            ],
            options={
                'verbose_name': 'Справочник модели',
                'verbose_name_plural': 'Справочники моделей',
            },
        ),
        migrations.CreateModel(
            name='ModelTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('transmission', 'Модель трансмиссии')], max_length=50, verbose_name='Категория модели')),
            ],
            options={
                'verbose_name': 'Справочник модели',
                'verbose_name_plural': 'Справочники моделей',
            },
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование Сервисных компаний')),
                ('groups', models.CharField(choices=[('service_company', 'Сервисная компания')], max_length=50, verbose_name='Группа Сервисных компаний')),
            ],
            options={
                'verbose_name': 'Справочник Сервисных компаний',
                'verbose_name_plural': 'Справочник Сервисных компаний',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Зав. № машины')),
                ('equipment_model', models.CharField(max_length=100, verbose_name='Модель оборудования')),
                ('engine_serial', models.CharField(max_length=100, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=100, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_serial', models.CharField(max_length=100, verbose_name=' Зав. № ведущего моста')),
                ('steerable_axle_serial', models.CharField(max_length=100, verbose_name='Зав. № управляемого моста')),
                ('delivery_contract', models.CharField(max_length=255, verbose_name='Договор поставки №, дата')),
                ('shipment_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('receiver', models.CharField(max_length=255, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=255, verbose_name='Адрес поставки (эксплуатации)')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('configuration', models.TextField(verbose_name='Комплектация (доп. опции)')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.customuser', verbose_name='Клиент')),
                ('drive_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.modeldrive_axle', verbose_name='Модель ведущего моста')),
                ('engine_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.modelengine', verbose_name='Модель двигателя')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.modelequipment', verbose_name='Модель техники')),
                ('steerable_axle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.modelsteering_axle', verbose_name='Модель управляемого моста')),
                ('transmission_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.modeltransmission', verbose_name='Модель трансмиссии')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='machines.servicename', verbose_name='Сервисная компания')),
            ],
        ),
    ]
