# Generated by Django 5.1 on 2024-09-04 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_hours', models.PositiveIntegerField()),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='machines.machine')),
                ('maintenance_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_organizations', to='machines.modelreference')),
                ('maintenance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_types', to='machines.modelreference')),
                ('service_company', models.ForeignKey(limit_choices_to={'groups__name': 'Service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_company_maintenances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
